name: Despliegue Manual a EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Desplegar a EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
        
      - name: Configurar Node.js e Instalar dependencias
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar dependencias
        run: npm install
        
      - name: Generar Documentación (JSDoc)
        run: npm run docs
        
      - name: Limpiar Archivos de Prueba antes del Despliegue
        run: find . -name '*.test.js' -delete
      
      - name: Preparar EC2 y Directorios
        uses: appleboy/ssh-action@v1.0.1 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo yum install nginx -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
            sudo mkdir -p /var/www/html/docs
            # Otorgar permisos al usuario SSH para que SCP pueda escribir
            sudo chown -R ${{ secrets.EC2_USER }}:nginx /var/www/html/
            sudo chmod -R 775 /var/www/html/

      - name: Copiar App a EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "index.html,styles.css,script"
          target: "/var/www/html"

      - name: Copiar Documentación a EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./docs"
          target: "/var/www/html"

      - name: Despliegue EC2 Completo
        run: echo "Sitio EC2 desplegado."