name: üíª 4. Despliegue Manual a EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Desplegar a EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar Artefacto de la App
        uses: actions/download-artifact@v4
        with:
          name: static-app-artifact
          path: ./app
          run-id: ${{ github.event.inputs.run_id }} 
          
      - name: Descargar Artefacto de Documentaci√≥n
        uses: actions/download-artifact@v4
        with:
          name: documentation-artifact
          path: ./docs
          run-id: ${{ github.event.inputs.run_id }}

      - name: Preparar EC2 y Directorios
        uses: appleboy/ssh-action@v1.0.1 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Asegura la instalaci√≥n y arranque de Nginx (usando yum, no amazon-linux-extras)
            sudo yum install nginx -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
            
            # Crea directorios y ajusta permisos
            sudo mkdir -p /var/www/html/docs
            sudo chown -R ${{ secrets.EC2_USER }}:nginx /var/www/html/
            sudo chmod -R 775 /var/www/html/

      - name: Copiar App a EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./app/*"
          target: "/var/www/html"

      - name: Copiar Documentaci√≥n a EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./docs/*"
          target: "/var/www/html/docs"

      - name: Despliegue EC2 Completo
        run: echo "Sitio EC2 desplegado."