name: Desplegar a EC2

on:
  push:
    -main
  workflow_dispatch:

jobs:
  deploy:
    name: Desplegar App Principal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Preparar Nginx y Permisos
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Detectar gestor de paquetes e instalar Nginx
            if command -v yum &> /dev/null; then
                sudo yum install nginx -y
            elif command -v apt &> /dev/null; then
                sudo apt update -y
                sudo apt install nginx -y
            fi

            sudo systemctl enable nginx
            sudo systemctl start nginx

            # Limpiar contenido antiguo y configurar permisos
            sudo rm -rf /var/www/html/*
            sudo chown -R $USER:$USER /var/www/html/
            sudo chmod -R 775 /var/www/html/

      - name: Copiar Archivos Principales a EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "index.html,styles.css,script" 
          target: "/var/www/html"

      - name: Despliegue EC2 Completo
        run: echo "App desplegada con éxito en la IP ${{ secrets.EC2_HOST }}"
