name: Desplegar a EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Desplegar App Principal
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Preparar Nginx y Permisos
        uses: appleboy/ssh-action@v1.0.1 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }} 

          script: |
            # Instalar Nginx
            sudo yum install nginx -y || sudo apt update -y && sudo apt install nginx -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
            
            # Limpiar contenido viejo y dar permiso al usuario SSH para escribir en /var/www/html/
            sudo rm -rf /var/www/html/*
            sudo chown -R ${{ secrets.EC2_USER }}: /var/www/html/
            sudo chmod -R 775 /var/www/html/

      - name: Copiar Archivos Principales a EC2
        uses: appleboy/scp-action@v0.1.7 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          source: "index.html,styles.css,script" 
          target: "/var/www/html"

      - name: Despliegue EC2 Completo
        run: echo "App desplegada con éxito."