name: Despliegue a EC2

on:
  workflow_dispatch:

jobs:
  ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de cÃ³digo
        uses: actions/checkout@v4

      - name: Copiando archivos a la instancia
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/site"   

      - name: Mover archivo a la direccion web
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo mkdir -p /var/www/my-site
            sudo cp -r /home/${{ secrets.EC2_USER }}/site/* /var/www/my-site/
            # permisos: prueba para Ubuntu/Nginx y AmazonLinux/Nginx
            sudo chown -R www-data:www-data /var/www/my-site 2>/dev/null | true
            sudo systemctl restart nginx || true