name: Despliegue a S3

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'ID de la ejecuci贸n del workflow de documentaci贸n (2_build_docs.yml) a desplegar.'
        required: true
        type: string

jobs:
  deploy:
    name: Desplegar a S3
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Descargar Artefacto de la App
        uses: actions/download-artifact@v4
        with:
          name: static-app-artifact
          path: ./app
          run-id: ${{ github.event.inputs.run_id }} 
          
      - name: Descargar Artefacto de Documentaci贸n
        uses: actions/download-artifact@v4
        with:
          name: documentation-artifact
          path: ./docs
          run-id: ${{ github.event.inputs.run_id }}

      - name: Limpiar Archivos de Prueba antes del Despliegue
        run: find ./app -name '*.test.js' -delete

      - name: Sincronizar App con S3
        run: aws s3 sync ./app s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Sincronizar Documentaci贸n con S3
        run: aws s3 sync ./docs s3://${{ secrets.S3_BUCKET_NAME }}/docs --delete

      - name: Despliegue S3 Completo
        run: echo "Sitio S3 desplegado."